### ISSUE TITLE
How to run this when server runs in Docker? (Pterodactyl)

### ISSUE THREAD

**Issue by Bazimek** [JonnyPtn/zomboi#10]
How to run this when server runs in Docker? (Pterodactyl)

**Comment by JonnyPtn** [comment]
You've got two options if you're running the server in a container:
- Run the bot inside the container
- Expose the log and map folders to the host machine and run the bot there

The bot just needs access to those two folders (and RCON if you want to use those features)

**Comment by Bazimek** [comment]
So can I just make a link to the files?

**Comment by JonnyPtn** [comment]
You can do whatever you want to as long as the bot can read the files from the given paths, so for example if you run the server in a docker container and the bot on the host, then you could run docker with the `-v` command to have those file paths on the host

**Comment by Bazimek** [comment]
OK thank you I will try it. I run the server in pterodactyls container.
