### ISSUE TITLE
User quit server?

### ISSUE THREAD

**Issue by Ramshackles** [JonnyPtn/zomboi#12]
Not sure if this is on my end but I never get discord notifications when people go offline, is it supposed to notify when quitting?

**Comment by JonnyPtn** [comment]
I haven't implemented it currently - When I tried it out I thought it was a bit spammy and not really useful information to know when someone leaves the server. I'm open to implementing it if there is demand for it though

**Comment by Ramshackles** [comment]
Maybe it could be an option to enable? Though I agree joining IS the most valuable info

**Comment by JonnyPtn** [comment]
I've added this now and also made all notifications configurable with env vars. They default to being enabled
