### ISSUE TITLE
RCON usage?

### ISSUE THREAD

**Issue by Yell420** [JonnyPtn/zomboi#14]
Hello wondering if there's an actual usage currently with rcon or if its still being developed?

was hoping it does something like the current built in discord bot that allows you to send messages from discord to in-game

**Comment by JonnyPtn** [comment]
Currently it's just used to get and set server options via the `option` command, but I could expose more of the rcon commands if desired

I would love to have the discord messages show in-game, but currently the only way the game allows you to do this is with the `servermsg` command which does message the chat but also shows the message in big red letters in the middle of the screen for everyone which is not very good so I haven't enabled it

there's a topic on the forum here where I've requested some changes to this command: https://theindiestone.com/forums/index.php?/topic/46687-server-to-player-messaging-alterations-needed/&tab=comments#comment-345257

**Comment by JonnyPtn** [comment]
Going to close this as it's not a specific request
