### ISSUE TITLE
Mod Compatibility with ChatBubble

### ISSUE THREAD

**Issue by Yell420** [JonnyPtn/zomboi#17]
Currently anytime someone talks when i have this mod ( it shows a bubble that they are typing above their head ) 

it will show the following 

[img=media/textures/bubble1.png]
[img=media/textures/bubble2.png]
[img=media/textures/bubble3.png]
[img=media/textures/bubble1.png]
[img=media/textures/bubble2.png]

anyway to ignore this so it has some compatibility with the mod and ignores the spam?

**Comment by JonnyPtn** [comment]
Yeah this should be relatively straightforward, can you share an excerpt from the chat log file of your server which includes one of these messages? then I can just filter them out

**Comment by Yell420** [comment]
Sure, i have attached the chat, its pretty much like this and the only thing that changes is the number for the bubble.png 

Appreciate it, thanks!


LOG  : General     , 1648614921099> 1,085,143,854> Message 'ChatMessage{chat=Local, author='taco', text='[img=media/textures/bubble2.png]'}' was sent to player with id '0' of chat '1'
LOG  : General     , 1648614921099> 1,085,143,854> Message 'ChatMessage{chat=Local, author='taco', text='[img=media/textures/bubble2.png]'}' was sent to player with id '8' of chat '1'
LOG  : General     , 1648614921099> 1,085,143,855> Message 'ChatMessage{chat=Local, author='taco', text='[img=media/textures/bubble2.png]'}' was sent to player with id '4' of chat '1'

**Comment by JonnyPtn** [comment]
Thanks, those messages should be filtered out now as of 3583b46
