### ISSUE TITLE
 DISCORD_TOKEN environment variable not found

### ISSUE THREAD

**Issue by Yell420** [JonnyPtn/zomboi#21]
2022-03-31 20:55:39,785:ERROR:zomboi: DISCORD_TOKEN environment variable not found

.. i have config.env with my discord token and i am unable to get this to work. Windows

**Comment by Yell420** [comment]
thanks for fixing chat bubble by the way, for now still using the older version (2-3  versions behind) with the updated chat.py changes to fix

**Comment by JonnyPtn** [comment]
The config file needs to just be named `.env` (not `config.env`)

**Comment by Grim-reap3r** [comment]
File "zomboi.py", line 55
    async def on_ready()
