### ISSUE TITLE
Any chance for a publish on Docker Hub?

### ISSUE THREAD

**Issue by Ramshackles** [JonnyPtn/zomboi#22]
This is just for ease of use/updating from with Unraid really

**Comment by JonnyPtn** [comment]
Yeah I'd like to do this at some point

**Comment by JonnyPtn** [comment]
I think I've set this up correctly now - so you can run `jonnyp/zomboi:latest` which should always run the latest image as I've set up github actions to push for every commit

Please let me know if you find any problems with this

**Comment by Ramshackles** [comment]
Excellent thanks - I can confirm I got it working on Unraid with the Container pulled from Docker Hub - loving it !!
