### ISSUE TITLE
support for additional skills like Driving, Piano, Lockpicking 

### ISSUE THREAD

**Issue by Yell420** [JonnyPtn/zomboi#24]
I run several mods that provide additional perks and they are being ignored currently it seems and not being sent to discord.

[Cooking=5, Fitness=5, Strength=5, Blunt=0, Axe=3, Sprinting=6, Lightfoot=2, Nimble=3, Sneak=2, Woodwork=10, Aiming=7, Reloading=5, Farming=3, Fishing=2, Trapping=6, PlantScavenging=10, Doctor=5, Electricity=8, MetalWelding=10, Mechanics=10, Spear=0, Maintenance=7, SmallBlade=0, LongBlade=1, SmallBlunt=1, Tailoring=10, Lockpicking=4, PseudonymousEdPiano=2, Driving=0]

**Comment by JonnyPtn** [comment]
This should be working now
