### ISSUE TITLE
Channel not working with ID

### ISSUE THREAD

**Issue by Yell420** [JonnyPtn/zomboi#25]
current build  I have confirmed this is the correct channel # that is working for a previous version of the bot.

**Comment by JonnyPtn** [comment]
Is this a channel ID or a channel name?

**Comment by Yell420** [comment]
i am using the channel ID, numbers like previously used in the config.py.

**Comment by Ramshackles** [comment]
try using the name of the channel instead in hyphens, in my case "pz"

after the change where it accepts channel as a string i couldnt use my id either - just hadnt gotten around to making a bug report

**Comment by Yell420** [comment]
> 

thanks, that did make it work. confirmed bug

**Comment by JonnyPtn** [comment]
OK yeah I see the problem - if an ID is passed we need to explicitly convert to an integer before trying to get the channel. Have fixed this in 7f7b6a8
