### ISSUE TITLE
After death, new character creation is not notified 

### ISSUE THREAD

**Issue by Grim-reap3r** [JonnyPtn/zomboi#28]
Hi.

When I run script

python zomboi.py

an error like that appears on my screen

  File "zomboi.py", line 55
    async def on_ready():
        ^
SyntaxError: invalid syntax

**Comment by Grim-reap3r** [comment]
I found a solution but now I have a different problem and one bug.

Problem:
When getting to maps just stuck does move at all is that correct?
https://prnt.sc/r6VicD9IX1J3

Bug:
When you die and create a new "person" bot on discord show only u left the server.
https://prnt.sc/f6BU8GuaCpxJ

Thx

**Comment by JonnyPtn** [comment]
Yeah your original issue was using an incorrect python version (must be 3.8+). The first problem in your second post is expected - that's just the end of the startup logging

Your last bug is a bug so I'll rename this issue appropriately

**Comment by Grim-reap3r** [comment]
any update ?

**Comment by JonnyPtn** [comment]
Should be working on latest version
