### ISSUE TITLE
RCON cant connect

### ISSUE THREAD

**Issue by Klegus** [JonnyPtn/zomboi#4]
Hi, rcon cant connect to server, but it works 100%.
I got this error in my console "Client sent invalid server password"
My rcon config looks like this "rconPassword ='La9B5ZJs'".
I add ' bcs without it i get this error on start "NameError: name 'La9B5ZJs' is not defined"

**Comment by JonnyPtn** [comment]
Yeah the quotes would be necessary as it's a string - have you double checked it matches up with the password you set in the `.ini` file for the server?

Also did you change the RCON port from the default (27015) as currently I've just got that hardcoded

Is there any other output in the console? It should also generate `zomboi.log` and `discord.log` files which may have more useful information

**Comment by Klegus** [comment]
Okay i fix it
