### ISSUE TITLE
Global chat echoed

### ISSUE THREAD

**Issue by xbelanch** [JonnyPtn/zomboi#40]
Bot is working pretty well :) but I found that messages in global chat are "echoed" as you can see at the next screenshot:

![ProjectZomboid64_2022-08-10_18-43-15](https://user-images.githubusercontent.com/23429/183968854-89387190-4a6e-49a8-b8b1-f7c0f713b24a.png)

I found it very annoying so I'm wondering if there's any option to disable it.

**Comment by petegilb** [comment]
The discord bot doesn't mirror any chat from discord and put it in the game. You are most likely using the builtin discord integration that project zomboid servers have

**Comment by JonnyPtn** [comment]
Yeah unfortunately this is a problem with the official integration that I experienced in the past too

**Comment by xbelanch** [comment]
For now I prefer the official (it's plain and less intrusive for my personal taste on discord) so I decided to comment `zomboi.add_cog(ChatHandler(zomboi, logPath))` line on zomboi.py. Perhaps it'd be useful have an option on the env file to disable it like the rest of notifications.
