### ISSUE TITLE
info command can exceed discords maximum message length

### ISSUE THREAD

**Issue by ftzero** [JonnyPtn/zomboi#41]
There is a 2000 character problem when using the !info username command.

Is there an update for this?

**Comment by petegilb** [comment]
nah this is a bug as of now. i fixed the !users command but I can look into the info command at some point

**Comment by petegilb** [comment]
@ftzero Could you test the branch from #45 and see if it works for you? Testing both the !info command and also !users would be awesome if you don't mind

**Comment by JonnyPtn** [comment]
Believe this shouldn't be an issue with the updated bot (`main` branch), It's using embeds for the player list now
