### ISSUE TITLE
Cant load worldmap.xml

### ISSUE THREAD

**Issue by Klegus** [JonnyPtn/zomboi#5]
I get this error "discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: '/home/container/media/maps/Muldraugh, KY/worldmap.xml'"

But worldmap.xml exists

**Comment by JonnyPtn** [comment]
Does it exist at that path or somewhere else? I can't think of any other reason why it would not be able to find the file if it's there in the expected path

**Comment by Klegus** [comment]
It is possible for us to talk on the discord, because it will be faster because I want to solve the problem quickly. Klegus#0420

**Comment by Klegus** [comment]
![image](https://user-images.githubusercontent.com/31622223/160080831-93edac9a-54a0-4ac3-be7c-c760a7bdbf30.png)
How you can see this file exists in this path
![image](https://user-images.githubusercontent.com/31622223/160080902-c98b9a29-b134-4a78-a544-cea50ec05482.png)

**Comment by Klegus** [comment]
this is my config map path 
![image](https://user-images.githubusercontent.com/31622223/160081003-647972ea-36fa-4ab1-ac72-36855a54cf3b.png)

**Comment by laurigates** [comment]
Could it be caused by insufficient permissions to the file or directory it is in? You could also debug this by creating the `maps/Muldraugh, KY` directory to another location (for example right next to `zomboi.py`), copying `worldmap.xml` there and adjusting `config.py` to point to this path.

**Comment by JonnyPtn** [comment]
This seems to not be an issue with the bot or anything I can control, it's just a complication getting the correct paths exposed from the container, so there's nothing to change for the bot here
