### ISSUE TITLE
Mount Error on Container Run

### ISSUE THREAD

**Issue by xBeEatNUx** [JonnyPtn/zomboi#55]
After building the image and trying to run the container, I am getting an error that complains about the invalid mount config...check below...

docker run -d -v zomboid-maps:~/steam/steamapps/common/ProjectZomboid/media/maps -v zomboid-logs:~/Zomboid/Logs -e DISCORD_TOKEN=XXX -e CHANNEL=XXX -e RCON_PASSWORD=XXX zomboi

docker: Error response from daemon: invalid volume specification: 'zomboid-maps:~/steam/steamapps/common/ProjectZomboid/media/maps': invalid mount config for type "volume": invalid mount path: '~/steam/steamapps/common/ProjectZomboid/media/maps' mount path must be absolute.

**Comment by JonnyPtn** [comment]
Not something I've seen before and I don't personally use the docker container, but based on the error about absolute paths I would guess it's because you're using `~` for the home folder? so perhaps try using absolute paths instead?

**Comment by xBeEatNUx** [comment]
yeah I figured this out last night, you have to use absolute paths. 
Thanks for the reply. 
Docker directions needs abit more flushing out but I got it to work and its solid, now I just need to see if I can change how its displayed in discord
