### ISSUE TITLE
Czech letters in chat are not working

### ISSUE THREAD

**Issue by Bazimek** [JonnyPtn/zomboi#57]
For example: ěšščěšřžý

![image](https://user-images.githubusercontent.com/17622398/198643291-516aaa16-e6ba-469b-a9ac-052c7dd1a944.png)
Top message is from official Discord integration
Bottom message is from zomboi

Can you look at that? Or is possible to turn off incoming chat?

**Comment by JonnyPtn** [comment]
I thought #44  would have fixed this, but perhaps it's the wrong encoding. Can you try changing it to use `utf-8` encoding and see if that fixes the issue?

**Comment by Bazimek** [comment]
I will try it.

**Comment by Bazimek** [comment]
With utf-8 the bot not even working (nothing is posted to Discord channel)

**Comment by Bazimek** [comment]
Changed back to latin-1 and my bot still nor working after restart? :(

**Comment by JonnyPtn** [comment]
What's the output? Did you definitely stop any other instances of the bot? I still think utf-8. may be the solution here

**Comment by Bazimek** [comment]
Problem is that I cannot test it atm because of https://github.com/JonnyPtn/zomboi/issues/59 ... my bot just not giving me anything can you help me with that please?

**Comment by Bazimek** [comment]
utf-8 did not help.
![image](https://user-images.githubusercontent.com/17622398/198867158-90c909bc-64d4-4f1b-b377-7563a21b0a81.png)
