### ISSUE TITLE
Users command can exceed discords maximum message length

### ISSUE THREAD

**Issue by Reagy** [JonnyPtn/zomboi#8]
If the length of the message exceeds 4k characters, discord refuses the message with a HTTP 400 error.
Currently the command wont work on servers with more than a few players as it goes over the limit.

Solution would be to split the message into multiple if it exceeds the 4k character length.

**Comment by JonnyPtn** [comment]
Yeah this is a problem I've come across too and need to fix, thanks!

I'll also probably look at reformatting the message so it uses less characters (currently the generated table has a bunch of extra fluff)

**Comment by Yell420** [comment]
was going to report this same issue.. 
glad its been reported

**Comment by JonnyPtn** [comment]
@Yell420 @Reagy  are you able to test with the fix in #32 ? My server doesn't have enough players to hit the limit

**Comment by ftzero** [comment]
There is a 2000 character problem when using the !info command.

Is there an update for this?

**Comment by JonnyPtn** [comment]
This should be working in latest version of the bot
