### ISSUE TITLE
Having an issue with discord module

### ISSUE THREAD

**Issue by SKYN1K** [JonnyPtn/zomboi#83]
Traceback (most recent call last):
  File "E:\project zomboid bot\zomboi.py", line 3, in <module>
    from chat import ChatHandler
  File "E:\project zomboid bot\chat.py", line 2, in <module>
    from discord.ext import tasks, commands
ModuleNotFoundError: No module named 'discord'

**Comment by leonbreidenbach-pc** [comment]
I got the exact same problem. I already re-installed the discord module but it just wont work. Any fixes yet?

**Comment by SKYN1K** [comment]
Didn't find a solution :(

**Comment by JonnyPtn** [comment]
Expect the problem is you didn't install python requirements before running - I've now moved to using c# so things are managed differently, so will close this
