### ISSUE TITLE
Skill Recovery Journal Mod - Perks.py 

### ISSUE THREAD

**Issue by Marsu2377** [JonnyPtn/zomboi#84]
I’m fairly certain that the skill recovery journal mod causes the Perks.py file to crash causing the common errors I have seen reported in other logged issues.

 After a player reads their journal, the bot will relay the skills into discord but then will cease to report players who have joined and skills they have learned. Players leaving and player count still works though. Turning off perks does not work as this still would effect the (hours survived) section. 
 
Current solution is to delete all log files before I start the server back up 
 
I have not tried any trouble shooting without this mod yet as I don’t want to remove this feature from the other players in the server but It would be nice to somehow integrate it into the code if this is causing the issue.

**Comment by Marsu2377** [comment]
> I’m fairly certain that the skill recovery journal mod causes the Perks.py file to crash causing the common errors I have seen reported in other logged issues.
> 
> After a player reads their journal, the bot will relay the skills into discord but then will cease to report players who have joined and skills they have learned. Players leaving and player count still works though. Turning off perks does not work as this still would effect the (hours survived) section.
> 
> Current solution is to delete all log files before I start the server back up
> 
> I have not tried any trouble shooting without this mod yet as I don’t want to remove this feature from the other players in the server but It would be nice to somehow integrate it into the code if this is causing the issue.

**Comment by WorkingClassKid** [comment]
I have updated the perks.py file on my fork of zomboi (python version) to support Skill Recovery Journal. The code is not very good (it's just a very quick fix) and I have translated the message to discord in french... you will need to translate it again in english...

https://github.com/buttsbucket/zomboi_python/blob/master/perks.py

**Comment by JonnyPtn** [comment]
Sorry for the delay! I've been reworking a lot of things lately, and tested with this mod and it works as expected (I think - when reading the journal it notifies each level up as they happen)

@buttsbucket  appreciate you looking at fixes for the python about this - While I don't plan to maintain it myself anymore it still exists on the `master` branch so happy to accept any pull requests there

**Comment by Marsu2377** [comment]
I have been using the script consistently for a couple weeks now since I received the email about this. I have not had any issues in player reporting and skills updates. No issues as well using the "Udderly Up To Date" mod and the auto restart script that's part of my .bat file. 

Thank you for finding a solution.
