### ISSUE TITLE
is this friendly install for newbie linux user?

### ISSUE THREAD

**Issue by ardu111** [JonnyPtn/zomboi#85]
Hello i want to use your bot for my server PZ does its friendly to install or its gona be hard for beginer linux user ? its ubuntu Ubuntu 22.04 vps and i use terminal for evrything.

Can i install this or its not really working atm?

**Comment by JonnyPtn** [comment]
It should be simple enough - there are quick start steps in the readme. I would note though that the `main` branch has less features than the `master` branch as I'm reimplementing it in dotnet and aiming to properly release that new version along with build 42

**Comment by ardu111** [comment]
I am sorry but i am total newbie in linux i got a vps and working zomboid server installed by https://pzwiki.net/wiki/Dedicated_server. Its on ubuntu 22.0.4. 

I menage to get work your script/bot from main and server commands was working from discord but the problem is that its forcing making new server in /root/zomboid/ and i am fighting this almost 2 days and cant get it to use my folder in /home/pzuser/Zomboid for config saves can u please explain me this like for a idiot i am not really famillar with linux still learning and i want really use it because commands on discord was working and i dont want to give vps password for my subadmins.. THanks for reading this and i am sorry for my grammar.

**Comment by Fallout001** [comment]
Any follow up on this? im currently attepting to set this up with my shockbyte Hosted PZ server and was looking for a little bit more help on how to setup within the zomboid files and how to run it once there
